apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-app
  labels:
    app: {{ .Values.appName }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if or .Values.existingEnv .Values.env }}
        envFrom:
        - secretRef:
          {{- if .Values.existingEnv }}
            name: {{ .Values.existingEnv }}
          {{- else }}
            name: {{ .Values.appName }}-env
          {{- end }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
      imagePullSecrets:
      - name: {{ .Values.registry.name }}-registry