apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-app
  labels:
    app: {{ .Values.appName }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.env }}
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value }}
        {{- end }}
        {{- end }}
        {{- if or .Values.existingSecret .Values.secret }}
        envFrom:
        - secretRef:
          {{- if .Values.existingSecret }}
            name: {{ .Values.existingSecret }}
          {{- else }}
            name: {{ .Values.appName }}-secret
          {{- end }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
      {{- if .Values.registry.name }}
      imagePullSecrets:
      - name: {{ .Values.registry.name }}-registry
      {{- end }}