---
{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
type: Opaque
data:
  {{- range $key, $value := .Values.secret }}
    {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}