---
{{- if .Values.registry.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registry.name }}-registry
data:
  .dockerconfigjson: {{ .Values.registry.secret }}
type: kubernetes.io/dockerconfigjson
{{- end }}