---
{{- if .Values.env_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-env
type: Opaque
data:
  {{- range $key, $value := .Values.env }}
    {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}