replicaCount: 1
appName: service

image:
  repository: harbor.pezl.local/project_mgmt/service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
  # nodePort: 30090

registry:
  name: harbor
  # secret: ewoJImF1dGhzIjogewoJCSJoYXJib3IucGV6bC5sb2NhbCI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZVRUJ6YzNjd2NtUT0iCgkJfQoJfQp9

ingress:
  enabled: false
  rewriteTarget: /
  tls:
    secretName: project-mgmt-tls
    hosts: project-mgmt.pezl.local
  host: project-mgmt.pezl.local
  paths: /
  pathType: Prefix

# env: 
#   OTEL_RESOURCE_ATTRIBUTES: "service.name=service"
#   OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4317 or http://localhost:4318 
#   OTEL_LOG_LEVEL: debug
  
# existingSecret: db-secret
# secret:
#   DB_HOST: db
#   DB_PORT: 5432
#   DB_USER: admin
#   DB_PASSWORD: P@ssw0rd
#   DB_NAME: project_mgmt
#   JWT_KEY: P@ssw0rd
